spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 123456
  main:
    allow-bean-definition-overriding: true
loader-config:
  customersSource: /home/elham/workspace/bank/files/input/customers
  accountsSource: /home/elham/workspace/bank/files/input/accounts
  transactionsSource: /home/elham/workspace/bank/files/input/transactions
  customersOutDestination: /home/elham/workspace/bank/files/output/customers
  accountsOutDestination: /home/elham/workspace/bank/files/output/accounts
  transactionsOutDestination: /home/elham/workspace/bank/files/output/transactions