spring:
  main:
    allow-bean-definition-overriding: true
generator-config:
     fileDestination: /home/elham/workspace/bank/files
     customerCount: 20
     accountMin: 1
     accountMax: 3
     transactionMax: 110
     transactionMin: 50
     transactionLimit: 1000
