spring:
  main:
    allow-bean-definition-overriding: true
files:
  destination: /home/elham/workspace/bank/files
customer-generator:
  customerCount: 20
accountGenerator:
  bound:
    min: 1
    max: 3
transaction-generator:
  transaction:
    max: 110
    min: 50
    limit: 1000
loader:
  thread:
    count: 4