spring:
  main:
    allow-bean-definition-overriding: true
generator-config:
     customerFileDestination: /home/elham/workspace/bank/files/input/customers
     accountFileDestination: /home/elham/workspace/bank/files/input/accounts
     transactionFileDestination: /home/elham/workspace/bank/files/input/transactions
     customerCount: 20
     accountMin: 1
     accountMax: 3
     transactionMax: 110
     transactionMin: 50
     transactionLimit: 1000
